# Usage: python scripts/gen_tables.py [output.s]   (default: src/tables.s)
# Description: Generate the quarter-turn move tables and the LED/turn tables
#              for the RV32I solver as Ripes-compatible assembly (.data).
# Input: none (derived from src/rubik_ref.py and src/led_model.py)
# Output: an assembly file with labels perm_mv_*, twist_mv_*, led_off,
#         cubie_rgb, turn_src, turn_add
# Dependencies: none (standard library only)
"""Generate ``tables.s`` holding only the move tables (no distance data).

Layout (all little-endian halfwords, stays 4-byte aligned):

* ``perm_mv_R``, ``perm_mv_B``, ``perm_mv_D``: 5040 entries each,
  stride ``PERM_STRIDE`` bytes. ``perm_mv_R`` is also the block base.
* ``twist_mv_R``, ``twist_mv_B``, ``twist_mv_D``: 729 entries + 1 zero pad
  each, stride ``TWIST_STRIDE`` bytes. The pad keeps every block 4-aligned.
* ``led_off``: 24 words, LED byte offset of sticker (position*3 + facelet).
* ``cubie_rgb``: 24 words, color of (cubie*3 + home facelet).
* ``turn_src`` / ``turn_add``: 3*7 bytes + 3 pad each, cubie-level quarter
  turns (same data as TURN_MAP) used to animate the solution.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from led_model import cubie_colors, led_offsets  # noqa: E402
from rubik_ref import (  # noqa: E402
    FACE_NAMES,
    NUM_CORNERS,
    NUM_PERMS,
    NUM_TWISTS,
    TURN_MAP,
    build_move_tables,
)

PER_LINE = 16
LED_TABLE_BYTES = 24 * 4 * 2 + 24 * 2  # led_off + cubie_rgb + turn_src + turn_add
TWIST_PADDED = NUM_TWISTS + 1
PERM_STRIDE = NUM_PERMS * 2
TWIST_STRIDE = TWIST_PADDED * 2
DEFAULT_OUT = Path(__file__).resolve().parent.parent / "src" / "tables.s"


def emit_block(label: str, values: list[int] | list[str], directive: str = ".half") -> list[str]:
    """Return assembly lines for one labeled array (.half by default)."""
    lines = [f"{label}:"]
    for i in range(0, len(values), PER_LINE):
        chunk = ", ".join(str(v) for v in values[i : i + PER_LINE])
        lines.append(f"    {directive} {chunk}")
    return lines


def turn_bytes(part: int) -> list[int]:
    """TURN_MAP digits as bytes: part 0 = source index, 1 = twist added."""
    lo = part * NUM_CORNERS
    return [int(c) for spec in TURN_MAP for c in spec[lo : lo + NUM_CORNERS]] + [0, 0, 0]


def render(perm_mv: list[list[int]], twist_mv: list[list[int]]) -> str:
    """Render both move tables as one assembly source string."""
    size = 3 * PERM_STRIDE + 3 * TWIST_STRIDE + LED_TABLE_BYTES
    lines = [
        "# Generated by scripts/gen_tables.py - do not edit by hand.",
        "# Move tables + LED/turn tables only (no distance information).",
        f"# perm stride = {PERM_STRIDE} bytes, twist stride = {TWIST_STRIDE} bytes,"
        f" total = {size} bytes",
        ".data",
    ]
    for face, name in enumerate(FACE_NAMES):
        lines += emit_block(f"perm_mv_{name}", perm_mv[face])
    for face, name in enumerate(FACE_NAMES):
        lines += emit_block(f"twist_mv_{name}", twist_mv[face] + [0])
    lines.append("# RENDER_BEGIN")
    lines.append("# LED tables")
    lines += emit_block("led_off", led_offsets(), ".word")
    lines += emit_block("cubie_rgb", [f"0x{c:06X}" for c in cubie_colors()], ".word")
    lines.append("# RENDER_END")
    lines.append("# Cubie-level quarter turns for the replay self-check")
    lines += emit_block("turn_src", turn_bytes(0), ".byte")
    lines += emit_block("turn_add", turn_bytes(1), ".byte")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    """Build the tables, preview them, and write the assembly file."""
    out = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUT
    perm_mv, twist_mv = build_move_tables()
    for face, name in enumerate(FACE_NAMES):
        print(f"perm_mv_{name}[:5]  = {perm_mv[face][:5]}")
        print(f"twist_mv_{name}[:5] = {twist_mv[face][:5]}")
    text = render(perm_mv, twist_mv)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text.splitlines())} lines,"
          f" {3 * PERM_STRIDE + 3 * TWIST_STRIDE + LED_TABLE_BYTES} bytes of table data)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
