/* Freestanding C version of src/solver.s, used as the gcc reference build.
 *
 * It does exactly what the assembly does for one input: build the two pruning
 * tables by BFS, parse and validate the state, invert it, rank it, run IDA*,
 * print the answer, replay it on the cubie arrays and check the cube is solved.
 * Move tables are linked in from the same generated tables.s. No libc, no
 * multiply, no divide: console output and exit go through Ripes ecalls.
 *
 * Build (see scripts/gcc_reference.sh):
 *   riscv64-unknown-elf-gcc -O2 -march=rv32i -mabi=ilp32 -ffreestanding \
 *       -nostdlib -Wl,--no-relax -T src/rv32.ld -DSTATE='"21345671111111"' ...
 */
#ifndef STATE
#define STATE "21345671111111"
#endif
#ifndef EXPECTED
#define EXPECTED 255 /* 255 = do not check the length */
#endif

enum { C = 7, NP = 5040, NT = 729, NT_STRIDE = 730, FACES = 3, MAX_DEPTH = 11, UNSEEN = 0xFF };

/* Generated by scripts/gen_tables.py; three faces back to back. */
extern const unsigned short perm_mv_R[], twist_mv_R[];
extern const unsigned char turn_src[], turn_add[];

static const char input[] = STATE;
static unsigned char perm_prune[NP], twist_prune[NT];
static unsigned short queue[NP];
static unsigned char st_perm[C], st_twist[C], inv_perm[C], inv_twist[C];
static unsigned char path[MAX_DEPTH + 1]; /* face << 2 | (turns - 1) */

static inline void put_char(int c)
{
    register int a0 __asm__("a0") = c;
    register int a7 __asm__("a7") = 11;
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7));
}

static void put_line(const char *s)
{
    while (*s)
        put_char(*s++);
    put_char('\n');
}

static inline void quit(int code)
{
    register int a0 __asm__("a0") = code;
    register int a7 __asm__("a7") = 93;
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7));
    for (;;)
        ;
}

/* BFS over one coordinate; stride is the table length per face. */
static void build_prune(const unsigned short *mv, unsigned stride, unsigned char *prune,
                        unsigned n)
{
    unsigned short *head = queue, *tail = queue + 1;
    for (unsigned i = 0; i < n; ++i)
        prune[i] = UNSEEN;
    prune[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        unsigned cur = *head++;
        unsigned char d = (unsigned char) (prune[cur] + 1);
        const unsigned short *tab = mv;
        for (int f = 0; f < FACES; ++f, tab += stride) {
            unsigned next = cur;
            for (int k = 0; k < 3; ++k) {
                next = tab[next];
                if (prune[next] == UNSEEN) {
                    prune[next] = d;
                    *tail++ = (unsigned short) next;
                }
            }
        }
    }
}

/* One clockwise quarter turn of the cubie arrays (replay only). */
static void apply_quarter(unsigned face)
{
    const unsigned char *src = turn_src + (face << 3) - face;
    const unsigned char *add = turn_add + (face << 3) - face;
    unsigned char p[C], o[C];
    for (int i = 0; i < C; ++i) {
        unsigned t = st_twist[src[i]] + add[i];
        p[i] = st_perm[src[i]];
        o[i] = (unsigned char) (t >= 3 ? t - 3 : t);
    }
    for (int i = 0; i < C; ++i) {
        st_perm[i] = p[i];
        st_twist[i] = o[i];
    }
}

/* Field types of a DFS frame. NARROW_FRAME packs them (24 bytes per frame);
 * the default uses full words, which RV32I handles without the extra
 * shift pairs that 8- and 16-bit fields need. */
#ifdef NARROW_FRAME
typedef unsigned short coord_t;
typedef signed char small_t;
#else
typedef unsigned coord_t;
typedef int small_t;
#endif

typedef struct {
    const unsigned short *ptab, *ttab;  /* move tables of the current face */
    coord_t perm, twist;                /* this node */
    coord_t cur_perm, cur_twist;        /* child being built */
    small_t last, face, turns;
} frame_t;

static inline int heuristic(unsigned perm, unsigned twist)
{
    int a = perm_prune[perm], b = twist_prune[twist];
    return a > b ? a : b;
}

static int search(unsigned perm, unsigned twist)
{
    frame_t stack[MAX_DEPTH + 1];
    for (int bound = heuristic(perm, twist); bound <= MAX_DEPTH; ++bound) {
        int depth = 0;
        if (bound == 0)
            return 0;
        stack[0] = (frame_t) {perm_mv_R, twist_mv_R, (coord_t) perm, (coord_t) twist,
                              0, 0, -1, 0, 0};
        while (depth >= 0) {
            frame_t *f = &stack[depth];
            if (f->face == FACES) {
                --depth;
                continue;
            }
            if (f->face == f->last || f->turns == 3) {
                ++f->face;
                f->turns = 0;
                f->ptab += NP;
                f->ttab += NT_STRIDE;
                continue;
            }
            if (f->turns == 0) {
                f->cur_perm = f->perm;
                f->cur_twist = f->twist;
            }
            f->cur_perm = f->ptab[f->cur_perm];
            f->cur_twist = f->ttab[f->cur_twist];
            int n = f->turns++;
            int h = heuristic(f->cur_perm, f->cur_twist);
            if (depth + 1 + h > bound)
                continue;
            path[depth] = (unsigned char) (f->face << 2 | n);
            if (h == 0 && depth + 1 == bound)
                return bound;
            stack[depth + 1] = (frame_t) {perm_mv_R, twist_mv_R, f->cur_perm, f->cur_twist,
                                          0, 0, f->face, 0, 0};
            ++depth;
        }
    }
    return -1;
}

static int solve(void)
{
    /* Factorial weights: adding fact[i] once per smaller element to the
     * right gives the Lehmer rank with no multiplication. */
    static const unsigned short fact[C] = {720, 120, 24, 6, 2, 1, 0};
    unsigned seen = 0, sum = 0, perm = 0, twist = 0;

    for (int i = 0; i < C; ++i) {
        unsigned p = (unsigned) (input[i] - '1');
        unsigned o = (unsigned) (input[i + C] - '1');
        if (p >= C || o >= 3 || (seen >> p & 1))
            return -1;
        st_perm[i] = (unsigned char) p;
        st_twist[i] = (unsigned char) o;
        seen |= 1U << p;
        sum += o;
    }
    if (input[2 * C])
        return -1;
    while (sum >= 3)
        sum -= 3;
    if (sum)
        return -1;

    for (int i = 0; i < C; ++i)
        inv_perm[st_perm[i]] = (unsigned char) i;
    for (int i = 0; i < C; ++i) {
        unsigned o = st_twist[inv_perm[i]];
        inv_twist[i] = (unsigned char) (o ? 3 - o : 0);
    }
    for (int i = 0; i < C; ++i)
        for (int j = i + 1; j < C; ++j)
            if (inv_perm[j] < inv_perm[i])
                perm += fact[i];
    for (int i = 0; i < 6; ++i)
        twist = (twist << 1) + twist + inv_twist[i];

    int len = search(perm, twist);
    if (len < 0)
        return -1;

    for (int i = len - 1; i >= 0; --i) { /* reverse, and invert each move */
        unsigned n = path[i] & 3;
        put_char("RBD"[path[i] >> 2]);
        if (n == 0)
            put_char('\'');
        else if (n == 1)
            put_char('2');
        if (i)
            put_char(' ');
    }
    put_char('\n');

    for (int i = len - 1; i >= 0; --i) /* replay: gate T5 */
        for (unsigned k = 3 - (path[i] & 3); k; --k)
            apply_quarter(path[i] >> 2);
    for (int i = 0; i < C; ++i)
        if (st_perm[i] != i || st_twist[i])
            return -2;
    if (EXPECTED != 255 && EXPECTED != len)
        return -2;
    return len;
}

void _start(void)
{
    build_prune(perm_mv_R, NP, perm_prune, NP);
    build_prune(twist_mv_R, NT_STRIDE, twist_prune, NT);
    int r = solve();
    if (r == -1)
        put_line("invalid");
    else if (r == -2)
        put_line("FAIL");
    quit(r < 0);
}
